### PR TITLE
Moc 96 use dsl for editing

### PR DESCRIPTION
**Pull request by jonathankap**
Here are some thoughts on interfaces for a Reactor class that could be used to by the editor to add DSL support. The plugin would attach a Reactor class to the DOM. This class would maintain a list of ModificationRequests, and apply those modifications to the DOM. It would also listen for mutations and re-apply the modifications as appropriate.

The Reactor defines two core events: onUrlLoaded and onPageLoaded - these are triggers that the plugin could use to query the backend for the right list of modifications. The specification for a "page" load, which is meant to be when the page changes on an SPA, is TBD.

The Reactor does not handle any interactions with the backend or user. Those - for storing modifications, editing, etc - would be handled in the plugin. The Reactor would only be used to apply the modifications to the live DOM.

Below is some pseudo-code of how I imagine Reactor being used:

1. Initial setup:
```
const reactor = new Reactor();
reactor.on('onUrlLoaded', (url) => {
  // fetch modifications for the given URL from the backend
  modifications: Array<ModificationRequest> = getModificationsForURL(url);
  // apply to reactor
  modifications.forEach(reactor.addModifications)
});
reactor.on('onPageLoaded', (url, page) => {
  // fetch modifications for the given URL from the backend
  modifications: Array<ModificationRequest> = getModificationsForPage(url, page);
  // apply to reactor
  modifications.forEach(reactor.addModifications)
});
reactor.attach();
```

2. Editor or AI adds a modification:
```
reactor.addModification({ ... })
```

3. Editor or AI undoes a modification
```
reactor.removeLastModification();
```

4. Turn on highlighting for a specific modification
```
const applied = reactor.getAppliedModifications().find(appliedModification => ...)
applied.setHighlight(true)
```

5. Remove an arbitrary modification from the list. This will unapply all modifications after
this one in the list, then remove the modification and reapply all later modifications
```
const appliedIndex = reactor.getAppliedModifications().findIndex(appliedModification => ...)
reactor.getAppliedModifications().splice(appliedIndex, 1)
```

My current questions are:
1. how do we detect/define SPA page changes to listen for?
2. should things like highlighting live in the reactor?
3. is there a generic way to handle appliedModifications as an array, or does it need to be a subclass?

## Summary by CodeRabbit

- **New Features**
	- Enhanced content processing capabilities with a new method for converting HTML elements to JSON.
	- Introduced a centralized approach for DOM modifications, improving maintainability and consistency.
	- Added support for complex modification scenarios through expanded interfaces, including a new action type, `replaceAll`.

- **Bug Fixes**
	- Removed deprecated functions to streamline content handling and improve performance.

- **Documentation**
	- Updated dependencies to reflect new capabilities provided by the @repo/reactor package.

- **Tests**
	- Expanded test coverage for DOM manipulation functions, ensuring robustness and accuracy in modifications.

### CODE REVIEW

**Comment by elg0nz** [comment]
I like it!

Your approach reminds me of Reactive JS - it was really ahead of its time. It's great to see Reactor living up to its name. I named this package Reactor not only to signal it does more than just DOM changes, but also to hint at its event-based/reactive nature.

Let's address your questions:

1. Detecting SPA page changes:
   I'll be frank and say I don't know 😅. I'll let @bkd705 tackle this question since he's more experienced with big JS apps.

2. Should highlighting be in Reactor?
   Yes. Reactor's secondary goal is to create an interface for LLMs to interact with demo apps. I'm aiming to have Reactor handle about 90% of all changes, including UI stuff like highlights and adding "edit me" boxes.

3. Handling appliedModifications:
   We can decide on this. An array should work fine.

**Comment by bkd705** [comment]
> I like it!
> 
> Your approach reminds me of Reactive JS - it was really ahead of its time. It's great to see Reactor living up to its name. I named this package Reactor not only to signal it does more than just DOM changes, but also to hint at its event-based/reactive nature.
> 
> Let's address your questions:
> 
> 1. Detecting SPA page changes:
>    I'll be frank and say I don't know 😅. I'll let @bkd705 tackle this question since he's more experienced with big JS apps.
> 2. Should highlighting be in Reactor?
>    Yes. Reactor's secondary goal is to create an interface for LLMs to interact with demo apps. I'm aiming to have Reactor handle about 90% of all changes, including UI stuff like highlights and adding "edit me" boxes.
> 3. Handling appliedModifications:
>    We can decide on this. An array should work fine.

I think we can potentially reuse some of this observermutation setup to listen for SPA changes, I might push back on that being a short term goal though since we're disabling most interactions at the moment so for now we can probably get away with assuming you're on a static page and add that functionality in later.

**Comment by bkd705** [comment]
One thing we will need and not sure how it fits into reactor is the ability to say "I want to do this same edit to all matching nodes on the page" vs "I only want to target this specific node even if there are other identical ones on the page"

**Comment by bkd705** [comment]
Can we maybe add a "bulk add" interface, I know under the hood it'll still be a loop but maybe would help clean up the usage if rather than the user needing to loop over each modification individually we can just pass an array of modifications to a function

**Comment by bkd705** [comment]
For #2 I might argue that it makes sense to have Reactor do the highlighting since it knows where the modifications are and can keep better track of them, but maybe we do it through a function where reactor gives the consumer the x/y coordinates and the consumer is responsible for actually drawing the box, that way its a bit agnostic to changes or maybe different types of highlighting etc

**Review by elg0nz — APPROVED** [review]
Looking great so far, I'm going to attempt to merge this in and find a way to plug it in behind a configuration setting so we can toggle it on/off as needed.

**Comment by elg0nz** [comment]
superseded by #148 but keeping around for reference.

**Pull request closed without merging**
